---
# tasks file for roles/apache
- name: Install Apache and firewalld packages
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
    state: present
- name: Start the httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
- name: start the firewall service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
- name: Add http port into firewall rules
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
- name: copy the jinja template.j2 to dev server /var/www/html/ directory
  ansible.builtin.template:
    src: template.j2
    dest: /var/www/html/index.html 

