---
- name: Using the timesync roles
  hosts: all
  vars:
    timesync_ntp_servers:
      - hostname: 192.168.56.102
        iburst: yes
    roles:
      - timesync
- name: Add NTP to firewalld
  hosts: all
  tasks:
    - name: enable ntp on firewalld
      ansible.posix.firewalld:
        service: ntp
        permanent: true
        state: enabled
        immediate: true
