---
- name: Collect Disk Space Information and print disk with more than 30% full
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: Get Disk Space Information
      shell: |
        df -h
      register: disk_space_output
  
    - name: Filter Disk Space Information
      set_fact:
        filtered_output: "{{ disk_space_output.stdout_lines[1:] | select('match', '^[^ ]+ +[^ ]+ +[^ ]+ +[^ ]+ +([3-9]|[1-9][0-9])[^0-9]%') | list }}"
  
    - name: Display Filtered Disk Space Information
      debug:
        var: filtered_output
