---
- name: node hwreport
  hosts: all
  ignore_errors: yes
  tasks:
    - name: Download the file
      ansible.builtin.get_url:
        url: http://content.bluefire.com/rhel9-repo/Ansible/hwreport.txt
        dest: /root/hwreport.txt

    - name: Collect report 1
      ansible.builtin.set_fact:
        HOSTNAME: "{{ ansible_hostname }}"
        MEMORY: "{{ ansible_memtotal_mb }}"
        BIOS: "{{ ansible_bios_version }}"
        CPU: "{{ ansible_processor }}"
        DISK_SIZE_VDA: "{{ ansible_devices['sda']['size'] }}"
    - name: Collect report 2
      ansible.builtin.set_fact:
        DISK_SIZE_VDB: "{{ ansible_devices['sdb']['size'] }}"
    - name: Copy the content to the managed node
      ansible.builtin.copy:
        content: |
          #hwreport
          HOSTNAME= {{ HOSTNAME | default('NONE') }}
          MEMORY= {{ MEMORY | default('NONE') }}
          BIOS= {{ BIOS | default('NONE') }}
          CPU= {{ CPU | default('NONE') }}
          DISK_SIZE_VDA= {{ DISK_SIZE_VDA | default('NONE') }}
          DISK_SIZE_VDB={{ DISK_SIZE_VDB | default('NONE') }}
        dest: /root/hwreport.txt
