---
- name: collect IP info
  hosts: dev
  tasks:
    - name: copy jinja template to generate myhosts file with ip info
      ansible.builtin.template:
        src: myhosts.j2
        dest: /etc/myhosts

