---
- name: create a logger cronjob
  hosts: all
  tasks:
    - name: Cronjob for logger
      ansible.builtin.cron:
        name: create logger
        user: student
        minute: "*/2"
        job: logger "EX294 in progress"
        state: present
